#!/usr/bin/env bash
# gives you information about the bestschool file

FILE="Bestschool"
if [ -e "$FILE" ]; then
    echo "$FILE file exists"
    if [ -s "$FILE" ]; then
	echo "Bestschool file is not empty"
    else
	echo "Bestschool file is empty"
    fi
    if [ -f "$FILE" ]; then
	echo "Bestschool is a regular file"
    fi
else
    echo "Bestschool file does not exist"
fi
